name: Generate docs

on:
  push:
    branches:
      - master
  # daily at midnight
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-latest:
    name: Get latest
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18.12.0
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build docs
        run: npm run build
      - name: Get examples
        run: npm run examples
      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Pushing latest docs
      